AWSTemplateFormatVersion: 2010-09-09 
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  SingaporeOfficeHours:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: SingaporeOfficeHours
      NoStackPrefix: 'True'
      Description: Office hours in Singapore
      ServiceToken: >-
        arn:aws:lambda:ap-southeast-1:646297494209:function:AWSInstanceScheduler-InstanceSchedulerMain
      Enforced: 'True'
      Hibernate: 'True'
      Timezone: Asia/Singapore
      Periods:
        - Description: Office hours on weekdays
          BeginTime: '08:00'
          EndTime: '18:00'
          WeekDays: Mon-Fri
