apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster1
  region: ${AWS_REGION}
  version: "1.21"

availabilityZones:
- ap-southeast-1a
- ap-southeast-1b
- ap-southeast-1c

addons:
- name: vpc-cni
- name: kube-proxy
- name: coredns
- name: aws-ebs-csi-driver

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}
