apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: nginx-sgp
spec:
  podSelector:
    matchLabels:
      app: mybusybox
  securityGroups:
    groupIds:
      - ${BUSYBOX_POD_SG_ID}