apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-appmesh-dev
subjects:
- kind: Group
  name: pinnacle:eks-appmesh-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-appmesh-dev
  apiGroup: rbac.authorization.k8s.io