apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: "arn:aws:iam::$ACCOUNT_ID:role/mycluster2-mycluster2Nodegroupmng1ngNodeGroupRole5-CGB5C26N84S8"
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: "arn:aws:iam::$ACCOUNT_ID:role/mycluster2-mng2-NodeInstanceRole-346HHL5L4HQ9"
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: "arn:aws:iam::$ACCOUNT_ID:role/mycluster2-mycluster2MastersRole66547EB4-7GMS178O1MR8"
      username: "arn:aws:iam::$ACCOUNT_ID:role/mycluster2-mycluster2MastersRole66547EB4-7GMS178O1MR8"
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::$ACCOUNT_ID:user/admin1
      username: arn:aws:iam::$ACCOUNT_ID:user/admin1
      groups:
        - system:masters


