apiVersion: v1
kind: Service
metadata:
  name: sample-backend-service-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: x-ray-sample-back-k8s
    tier: backend
  ports:
  - name: sample-backend-service-lb-port
    protocol: TCP
    port: 80
    targetPort: 8080