apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: web
  namespace: wordsmith
spec:
  awsName: web
  podSelector:
    matchLabels:
      app: words-web
  listeners:
    - portMapping:
        port: 80
        protocol: tcp  
  serviceDiscovery:
    dns:
      hostname: web.wordsmith.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceRef:
          name: words
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: web
  namespace: wordsmith
spec:
  awsName: web
  provider:
    virtualNode:
      virtualNodeRef:
        name: web
