apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynginx2
    project: tiger
  name: mynginx2
  namespace: fp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx2
      project: tiger
  strategy: {}
  template:
    metadata:
      labels:
        app: mynginx2
        project: tiger
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mynginx2
            topologyKey: "topology.kubernetes.io/zone"
      containers:
      - image: nginx
        name: nginx
        resources: {}
